sudo: required
#sudo:required gives us super user level permissions to execute this build
services:
  - docker
#tells travis ci to use a copy of docker
before_install:
  - docker build -t icebluemink7/docker-react -f Dockerfile.dev .
#has a series of commands that executers before the test is ran
#building docker image befoer the test runs with Dockerfile.dev with the current directory
#script is all the different commands that need to be ran when our test executes
script:
  - docker run -e CI=true icebluemink7/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-319432293873"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
